// Generated by view binder compiler. Do not edit!
package com.example.cityinformation.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.ScrollView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.cityinformation.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityStagesBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final ImageView busstans;

  @NonNull
  public final ImageView college;

  @NonNull
  public final ImageView government;

  @NonNull
  public final ImageView hospitals;

  @NonNull
  public final ImageView hotels;

  @NonNull
  public final ImageView police;

  @NonNull
  public final ImageView tor;

  private ActivityStagesBinding(@NonNull ScrollView rootView, @NonNull ImageView busstans,
      @NonNull ImageView college, @NonNull ImageView government, @NonNull ImageView hospitals,
      @NonNull ImageView hotels, @NonNull ImageView police, @NonNull ImageView tor) {
    this.rootView = rootView;
    this.busstans = busstans;
    this.college = college;
    this.government = government;
    this.hospitals = hospitals;
    this.hotels = hotels;
    this.police = police;
    this.tor = tor;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityStagesBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityStagesBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_stages, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityStagesBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.busstans;
      ImageView busstans = ViewBindings.findChildViewById(rootView, id);
      if (busstans == null) {
        break missingId;
      }

      id = R.id.college;
      ImageView college = ViewBindings.findChildViewById(rootView, id);
      if (college == null) {
        break missingId;
      }

      id = R.id.government;
      ImageView government = ViewBindings.findChildViewById(rootView, id);
      if (government == null) {
        break missingId;
      }

      id = R.id.hospitals;
      ImageView hospitals = ViewBindings.findChildViewById(rootView, id);
      if (hospitals == null) {
        break missingId;
      }

      id = R.id.hotels;
      ImageView hotels = ViewBindings.findChildViewById(rootView, id);
      if (hotels == null) {
        break missingId;
      }

      id = R.id.police;
      ImageView police = ViewBindings.findChildViewById(rootView, id);
      if (police == null) {
        break missingId;
      }

      id = R.id.tor;
      ImageView tor = ViewBindings.findChildViewById(rootView, id);
      if (tor == null) {
        break missingId;
      }

      return new ActivityStagesBinding((ScrollView) rootView, busstans, college, government,
          hospitals, hotels, police, tor);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
